version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ap-southeast-1 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t classy .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker tag classy:latest 925840096513.dkr.ecr.ap-southeast-1.amazonaws.com/classy:latest
      - docker push 925840096513.dkr.ecr.ap-southeast-1.amazonaws.com/classy:latest
      - echo Writing image definitions file...